language: android
android:
   components:
   - tools
   - platform-tools
   - android-23
   - build-tools-23.0.2
   - extra

jdk: oraclejdk7

notifications:
  email: false

sudo: false

before_script:
 - chmod +x gradlew

script:
  - ./gradlew clean build
