sudo: false
language: android
jdk: 
 - oraclejdk8
 
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
 
android:
 components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  #- platform-tools
  - tools

  # The BuildTools version used by your project
  - build-tools-19.1.0

  # The SDK version used to compile your project
  - android-19
  
  # Additional components
  - extra-android-m2repository
  
  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-19
  
  
before_script:
 - chmod +x gradlew
 - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

script:
 - ./gradlew build connectedCheck
